name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm install
      env:
          CI: false
    - name: Generate build
      run: CI=false npm run build
    - name: jekyll-deploy-gh-pages
      uses: BryanSchuetz/jekyll-deploy-gh-pages@v2.0
      with:
        deploy_key: ${{secrets.ALGO_VIZ}}
        publish_dir: ./build

